FROM --platform=linux/amd64 ubuntu:24.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake git

COPY . /repo
WORKDIR /repo
RUN git submodule update --init --recursive
WORKDIR /repo/build
RUN cmake .. -DARK_BUILD_EXE=ON -DCMAKE_INSTALL_PREFIX=/install -DCMAKE_BUILD_TYPE=Release
RUN make -j$(nproc)
RUN make install

FROM ubuntu:24.04 as package
COPY --from=builder /install /install
ENV LD_LIBRARY_PATH=/install/lib
